var _passes_2_convert_zhl_to_zml_2_patterns_8h =
[
    [ "zml::ZhlOpLoweringPattern< Op >", "classzml_1_1_zhl_op_lowering_pattern.html", "classzml_1_1_zhl_op_lowering_pattern" ],
    [ "zml::ConstructorLowering< Op >", "classzml_1_1_constructor_lowering.html", "classzml_1_1_constructor_lowering" ],
    [ "zml::ZhlLiteralLowering", "classzml_1_1_zhl_literal_lowering.html", "classzml_1_1_zhl_literal_lowering" ],
    [ "zml::ZhlLiteralStrLowering", "classzml_1_1_zhl_literal_str_lowering.html", "classzml_1_1_zhl_literal_str_lowering" ],
    [ "zml::ZhlParameterLowering", "classzml_1_1_zhl_parameter_lowering.html", "classzml_1_1_zhl_parameter_lowering" ],
    [ "zml::ZhlConstructLowering", "classzml_1_1_zhl_construct_lowering.html", "classzml_1_1_zhl_construct_lowering" ],
    [ "zml::ZhlConstrainLowering", "classzml_1_1_zhl_constrain_lowering.html", "classzml_1_1_zhl_constrain_lowering" ],
    [ "zml::ZhlGlobalRemoval", "classzml_1_1_zhl_global_removal.html", "classzml_1_1_zhl_global_removal" ],
    [ "zml::ZhlDirectiveRemoval", "classzml_1_1_zhl_directive_removal.html", "classzml_1_1_zhl_directive_removal" ],
    [ "zml::ZhlGenericRemoval", "classzml_1_1_zhl_generic_removal.html", "classzml_1_1_zhl_generic_removal" ],
    [ "zml::ZhlSpecializeRemoval", "classzml_1_1_zhl_specialize_removal.html", "classzml_1_1_zhl_specialize_removal" ],
    [ "zml::ZhlDeclarationRemoval", "classzml_1_1_zhl_declaration_removal.html", "classzml_1_1_zhl_declaration_removal" ],
    [ "zml::ZhlDefineLowering", "classzml_1_1_zhl_define_lowering.html", "classzml_1_1_zhl_define_lowering" ],
    [ "zml::ZhlSuperLoweringInFunc", "classzml_1_1_zhl_super_lowering_in_func.html", "classzml_1_1_zhl_super_lowering_in_func" ],
    [ "zml::ZhlSuperLoweringInMap", "classzml_1_1_zhl_super_lowering_in_map.html", "classzml_1_1_zhl_super_lowering_in_map" ],
    [ "zml::ZhlSuperLoweringInBlock", "classzml_1_1_zhl_super_lowering_in_block.html", "classzml_1_1_zhl_super_lowering_in_block" ],
    [ "zml::ZhlSuperLoweringInSwitch", "classzml_1_1_zhl_super_lowering_in_switch.html", "classzml_1_1_zhl_super_lowering_in_switch" ],
    [ "zml::ZhlExternLowering", "classzml_1_1_zhl_extern_lowering.html", "classzml_1_1_zhl_extern_lowering" ],
    [ "zml::ZhlLookupLowering", "classzml_1_1_zhl_lookup_lowering.html", "classzml_1_1_zhl_lookup_lowering" ],
    [ "zml::ZhlSubscriptLowering", "classzml_1_1_zhl_subscript_lowering.html", "classzml_1_1_zhl_subscript_lowering" ],
    [ "zml::ZhlArrayLowering", "classzml_1_1_zhl_array_lowering.html", "classzml_1_1_zhl_array_lowering" ],
    [ "zml::ZhlCompToZmirCompPattern", "classzml_1_1_zhl_comp_to_zmir_comp_pattern.html", "classzml_1_1_zhl_comp_to_zmir_comp_pattern" ],
    [ "zml::ZhlRangeOpLowering", "classzml_1_1_zhl_range_op_lowering.html", "classzml_1_1_zhl_range_op_lowering" ],
    [ "zml::ZhlMapLowering", "classzml_1_1_zhl_map_lowering.html", "classzml_1_1_zhl_map_lowering" ],
    [ "zml::ZhlBlockLowering", "classzml_1_1_zhl_block_lowering.html", "classzml_1_1_zhl_block_lowering" ],
    [ "zml::ZhlReduceLowering", "classzml_1_1_zhl_reduce_lowering.html", "classzml_1_1_zhl_reduce_lowering" ],
    [ "zml::ZhlSwitchLowering", "classzml_1_1_zhl_switch_lowering.html", "classzml_1_1_zhl_switch_lowering" ],
    [ "zml::ZhlBackLowering", "classzml_1_1_zhl_back_lowering.html", "classzml_1_1_zhl_back_lowering" ],
    [ "zml::ZhlConstructGlobalLowering", "classzml_1_1_zhl_construct_global_lowering.html", "classzml_1_1_zhl_construct_global_lowering" ],
    [ "zml::ZhlGetGlobalLowering", "classzml_1_1_zhl_get_global_lowering.html", "classzml_1_1_zhl_get_global_lowering" ]
];