//===- Attrs.h - ZML Attributes ---------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// This file includes the autogenerated headers of the ZML attributes defined
// in Attrs.td.
//
//===----------------------------------------------------------------------===//

#pragma once

#include <mlir/IR/DialectImplementation.h>

namespace zhl {
class TypeBinding;
class TypeBindings;
} // namespace zhl

// Include TableGen'd declarations
#define GET_ATTRDEF_CLASSES
#include <zklang/Dialect/ZML/IR/Attrs.h.inc>
