//===- Dialect.h - ZML Dialect ----------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// This file includes the autogenerated header file from Dialect.td.
//
//===----------------------------------------------------------------------===//

#pragma once

#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/Dialect/Index/IR/IndexDialect.h>
#include <mlir/Dialect/SCF/IR/SCF.h>
#include <mlir/IR/Dialect.h>

#include <zklang/Dialect/ZML/IR/Dialect.h.inc>

namespace mlir {
class MLIRContext;
}

namespace zml {

/// Loads extensions that enable interactions between ZML and LLZK.
void loadLLZKDialectExtensions(mlir::MLIRContext &);

} // namespace zml
