//===- Ops.h - ZML operations -----------------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// This file includes ZML operation definitions in the autogenerated file
// created from Ops.td.
//
//===----------------------------------------------------------------------===//

#pragma once

#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringRef.h>
#include <mlir/Bytecode/BytecodeOpInterface.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinOps.h>
#include <mlir/IR/OpDefinition.h>
#include <mlir/IR/OpImplementation.h>
#include <mlir/Interfaces/CallInterfaces.h>
#include <mlir/Interfaces/ControlFlowInterfaces.h>
#include <mlir/Interfaces/DataLayoutInterfaces.h>
#include <mlir/Interfaces/FunctionInterfaces.h>
#include <mlir/Interfaces/InferTypeOpInterface.h>
#include <mlir/Interfaces/SideEffectInterfaces.h>
#include <zklang/Dialect/ZML/IR/OpInterfaces.h> // IWYU pragma: keep
#include <zklang/Dialect/ZML/IR/Types.h>        // IWYU pragma: keep

namespace zml {

/// Tag for ComponentOp build method
struct IsBuiltIn {};

} // namespace zml

// Include TableGen'd declarations
#define GET_OP_CLASSES
#include <zklang/Dialect/ZML/IR/Ops.h.inc>
