//===- PassDetail.h - Pass inner details -------------------------*- C++ -*-===//
//
// Part of the LLZK Project, under the Apache License v2.0.
// See LICENSE.txt for license information.
// Copyright 2025 Veridise Inc.
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// This file includes the autogenerated internal definitions of the passes
// defined in Passes.td in the same directory.
//
//===----------------------------------------------------------------------===//

#pragma once

#include <llzk/Dialect/LLZK/IR/Dialect.h>  // IWYU pragma: keep
#include <llzk/Dialect/Struct/IR/Ops.h>    // IWYU pragma: keep
#include <mlir/Pass/Pass.h>                // IWYU pragma: keep
#include <zirgen/Dialect/ZHL/IR/ZHL.h>     // IWYU pragma: keep
#include <zklang/Dialect/ZML/IR/Dialect.h> // IWYU pragma: keep
#include <zklang/Dialect/ZML/IR/Ops.h>     // IWYU pragma: keep

namespace zklang {

#define GEN_PASS_CLASSES
#include <zklang/Passes/Passes.h.inc>

} // namespace zklang
