name: Changelog validator
on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow-changelog-validate:
    uses: Veridise/open-source-release-helpers/.github/workflows/changelog-validator.yml@main
    secrets: inherit
