name: Changelog validator
on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - README.md
      - docs
      - test
      - unittests

jobs:
  call-workflow-changelog-validate:
    uses: Veridise/open-source-release-helpers/.github/workflows/changelog-validator.yml@main
    secrets: inherit
