on:
  pull_request:
    types: ['opened', 'ready_for_review']
    branches: [ $default-branch ]


name: Transition Issue to In Review

jobs:
  call-workflow:
    uses: Veridise/.github/.github/workflows/jira-in-review-transition-core.yml@main
    with:
      head-ref: ${{ github.head_ref }}
      is-draft: ${{ github.event.pull_request.draft }}
    secrets: inherit
